### ISSUE TITLE
*Addition* First and Last page pagination

### ISSUE THREAD

**Issue by developersteve** [MongoDB-Rox/phpMoAdmin-MongoDB-Admin-Tool-for-PHP#13]
Ive added this to our versions
#### line 2351####

`$paginator = "<a href='".$baseUrl . '?' . http_build_query($get) . '&collection=' . urlencode($collection)."'>|&lt;</a> " . $paginator;`
#### line 2357####

`$paginator = $paginator." <a href='".$baseUrl . '?' . http_build_query($get) . '&collection=' . urlencode($collection)."&skip=".($mo->mongo['count'] - $objCount)."'>&gt;|</a> ";`

**Comment by MongoDB-Rox** [comment]
Good suggestion, this functionality is added in Version 1.1.4
