### ISSUE TITLE
Detecting phpMoAdmin with Wappalyzer?

### ISSUE THREAD

**Issue by SebastianLopienski** [MongoDB-Rox/phpMoAdmin-MongoDB-Admin-Tool-for-PHP#25]
It would be nice to be able to detect phpMoAdmin instances with https://github.com/AliasIO/Wappalyzer. Do you have some public demo instance of phpMoAdmin, so that I could have a look and create Wappalyzer detection rules?

**Comment by MongoDB-Rox** [comment]
There is no official public demo, but you are free to create one - just drop the file on any webserver that you are comfortable with the general public modifying your database.
