### ISSUE TITLE
Deprecated: moadminModel::_mongo()

### ISSUE THREAD

**Issue by terrylinooo** [MongoDB-Rox/phpMoAdmin-MongoDB-Admin-Tool-for-PHP#28]
Deprecated: moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in xxxxxx on line 297

I just use this, but error occurs.

**Comment by MongoDB-Rox** [comment]
Terry, you are using an older version of phpMoAdmin, this was updated to utilize the newer MongoClient class in version 1.1.3
